import Head from 'next/head';
import Navbar from '../components/navbar/Navbar';
import LandingPage from '../components/landingPage/LandingPage';
import About from '../components/about/About.js';
import Project from '../components/project/Project';
import Blogs from '../components/blogs/Blogs.js';
import Contact from '../components/contact/Contact';
import Footer from '../components/footer/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Grishma - Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <LandingPage />
        <About />
        <Project />
        <Contact />
        <Blogs />
        <Footer />
      </div>
    </div>
  );
}
